on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


name: Linux installation
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: pip install .
            - name: Test import
              run: python -c "import hello_geo; print('hello_geo import successful')"
